"""add_independent_test_set_support

Revision ID: c93348c4f6f5
Revises: b2c3d4e5f6a7
Create Date: 2026-07-01 14:51:50.329612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93348c4f6f5'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_jti'), ['jti'], unique=True)

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_test_set', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('source_dataset_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('collection_method', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_datasets_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_is_test_set'), ['is_test_set'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_source_dataset_id'), ['source_dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_status'), ['status'], unique=False)
        batch_op.create_foreign_key(None, 'datasets', ['source_dataset_id'], ['id'])

    with op.batch_alter_table('model_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('independent_test_dataset_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('independent_accuracy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('independent_f1_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('independent_metrics_json', sa.Text(), nullable=True))
        batch_op.create_index('ix_model_records_accuracy', ['accuracy'], unique=False)
        batch_op.create_index('ix_model_records_f1_score', ['f1_score'], unique=False)
        batch_op.create_index('ix_model_records_framework', ['framework'], unique=False)
        batch_op.create_index('ix_model_records_model_type', ['model_type'], unique=False)
        batch_op.create_index('ix_model_records_r2', ['r2'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_records_status'), ['status'], unique=False)
        batch_op.create_foreign_key(None, 'datasets', ['independent_test_dataset_id'], ['id'])

    with op.batch_alter_table('training_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_jobs_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_jobs_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_training_jobs_owner_status', ['owner_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_jobs_status'))
        batch_op.drop_index('ix_training_jobs_owner_status')
        batch_op.drop_index(batch_op.f('ix_training_jobs_owner_id'))
        batch_op.drop_index(batch_op.f('ix_training_jobs_dataset_id'))

    with op.batch_alter_table('model_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_model_records_status'))
        batch_op.drop_index('ix_model_records_r2')
        batch_op.drop_index('ix_model_records_model_type')
        batch_op.drop_index('ix_model_records_framework')
        batch_op.drop_index('ix_model_records_f1_score')
        batch_op.drop_index('ix_model_records_accuracy')
        batch_op.drop_column('independent_metrics_json')
        batch_op.drop_column('independent_f1_score')
        batch_op.drop_column('independent_accuracy')
        batch_op.drop_column('independent_test_dataset_id')

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_datasets_status'))
        batch_op.drop_index(batch_op.f('ix_datasets_source_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_owner_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_is_test_set'))
        batch_op.drop_index(batch_op.f('ix_datasets_is_public'))
        batch_op.drop_column('collection_method')
        batch_op.drop_column('source_dataset_id')
        batch_op.drop_column('is_test_set')

    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_jti'))

    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
